  name: Monitor Gist and Create Issue

on:
  schedule:
    - cron: "*/5 * * * *"  # 5분마다 실행
  workflow_dispatch:  # 수동 트리거 추가

jobs:
  monitor_gist:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Check for Gist updates
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gist_id="3d83fb50ad69da1b7837a1beafd69cd0"  # Gist의 ID를 설정하세요.
        response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/gists/$gist_id")
        updated_at=$(echo $response | jq -r '.updated_at')

        last_updated_file=".last_updated"

        if [ -f $last_updated_file ]; then
          last_updated=$(cat $last_updated_file)
        else
          last_updated=""
        fi

        if [ "$updated_at" != "$last_updated" ]; then
          echo "New update detected in Gist"
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title":"New Gist Update","body":"A new update has been made to the Gist."}' \
            https://api.github.com/repos//thouikor/gistissue/issues

          echo $updated_at > $last_updated_file
        else
          echo "No new updates detected"
        fi

