name: GIST Update Issue

on:
  push:
    paths:
      - '**/*.txt'  # txt 파일이 푸시될 때만 트리거됨

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create GitHub Issue
      uses: peter-evans/create-issue-from-file@v2
      with:
        title: "New GIST file update"
        content: |
          A new GIST file has been updated. Please review the changes.
        labels: update
